### PR TITLE
Set __version__ from its own file

### LINKED ISSUE #16: pip install fails on a clean system
```
$ mkvirtualenv sklearn2pmml
(sklearn2pmml) $ pip install git+https://github.com/jpmml/sklearn2pmml.git
Collecting git+https://github.com/jpmml/sklearn2pmml.git
  Cloning https://github.com/jpmml/sklearn2pmml.git to /tmp/pip-vk80_S-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-vk80_S-build/setup.py", line 3, in <module>
        from sklearn2pmml import __license__, __version__
      File "sklearn2pmml/__init__.py", line 3, in <module>
        from sklearn.base import BaseEstimator
    ImportError: No module named sklearn.base
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-vk80_S-build/
```

The reason is that pip needs to execute setup.py to be get the needed install dependencies. Before that has been executed you can't reference them. Just importing __version__ and __licensor__ from the __init__.py will in turn import the dependencies.

This is quite annoying and can be fixed in a few different ways. The simplest one is to just write the strings. in the setup.py as well. Not a problem for __license__ which will rarely change but maybe annoying for __version__ which you bump every now and then.

I suggest copying the string for __licence__ and moving __version__ to version.py and just import it in sklearn2pmml/__init__.py and setup.py, but modify the sys.path in setup.py to be able to treat version.py as its own package. I can send a pull-request.

### PR DESCRIPTION
**Pull request by jooon**
Will make it possible to pip install sklearn2pmml again from a clean
system. Fixes #16

### CODE REVIEW

**Comment by infiton** [comment]
@vruusmann what's the thinking on this? I also needed to apply a patch to get this deployed https://github.com/infiton/sklearn2pmml/commit/267b879289b7a9254a6c97652c4f03526ea7e0c5

**Comment by vruusmann** [comment]
@infiton The thinking goes that `sklearn2pmml` has "hard dependence" on `scikit-learn`. It doesn't make sense to install `sklearn2pmml` if you haven't **_already_** installed `scikit-learn`.

And if you're speaking about installing into a clean environment, then simply do:
```
$ pip install sklearn
$ pip install sklearn2pmml
```

Maybe I'm too old-fashioned, but I dislike the idea that some tiny innocent-looking package (eg. `sklearn2pmml`) could alter my programming/package environment in a major way (eg. by automatically installing/updating `scikit-learn`, `scipy`, `numpy` etc.).

**Comment by infiton** [comment]
@vruusmann the issue for me arises when using docker, where my base image actually does have `sklearn` already installed but it doesn't have `sklearn_pandas`.

The problem with doing:
```
$ pip install sklearn_pandas
$ pip install sklearn2pmml
```

is that in our docker image builder different installs happen in parallel, so `pip install sklearn2pmml` gets called before `pip install sklearn_pandas` can complete.

**Comment by vruusmann** [comment]
@infiton But wouldn't the following install packages in the specified order:
```
$ pip install sklearn sklearn_pandas sklearn2pmml
```

**Comment by infiton** [comment]
from https://pip.pypa.io/en/stable/reference/pip_install/#installation-order

```
Installation Order
As of v6.1.0, pip installs dependencies before their dependents, i.e. in "topological order". This is the only commitment pip currently makes related to order. While it may be coincidentally true that pip will install things in the order of the install arguments or in the order of the items in a requirements file, this is not a promise.
```

**Pull request closed without merging**
